# Generated by Django 6.1 on 2026-08-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_student_session_attendance',
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'date')},
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='room',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='session',
        ),
    ]
