# Generated by Django 6.1 on 2026-08-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_attendancerecord_unique_student_session_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='room',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='classsession',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
