# Generated by Django 6.1 on 2026-08-19 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_classsession_room_classsession_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='class_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.classsession'),
        ),
    ]
