# Generated by Django 6.1 on 2026-08-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendancerecord_class_session'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'class_session')},
        ),
    ]
